### ISSUE TITLE
Empa HDR Data Base is now available at https://doi.org/10.5281/zenodo.7861544 

### ISSUE THREAD

**Issue by zollikerpeter** [QUALINET/databases#28]
*If you want to add a new database, please edit this post and fill out the following info. Please keep the `yaml` marker intact and only replace the values.*

```yaml
- title: The title of the database
- database: A longer name for the database (can be the same as title)
- categories: Any of `Image`, `Video`, `Audiovisual`, `Audio`
- excerpt: A short description (optional)
- author: The institution/author
- partner: 'true' if you are a QUALINET partner (optional), otherwise false
- external_link: A link to the database
- doi: A Digital Object Identifier (DOI) (optional)
- access: A description of how to access the database (e.g. tell people to follow the link, fill out a form, etc.)
- publicly_available: 'true' if the database is publicly accessible
- citation: A short description of how to cite the database (optional)
- references: A list of references (optional), e.g.
    JD20a: John Doe, A sample reference, 2020`
    JD20b: John Doe, Another sample reference, 2020`
- license: The name of the license, or any custom license statements (optional but recommended)
- contact_name: A name or description of how to contact the author(s)
- contact_email: A contact email (this will be public)
- tags:
    - tag1
    - tag2
    - tag3 (these are all optional)
- subjective_scores: 'true' if the database has subjective scores (optional)
- total: Total number of sequences in the database (optional)
- src: The number of SRCs (optional)
- hrc: The number of HRCs (optional)
- ratings: Number of subjective ratings (optional)
- resolution: Resolutions used (optional)
- method: Subjective test method used (optional)
```

*If you want, add a longer description of the database here:*

**(add a longer description here)**

*Note: You can use Markdown formatting to highlight text, include external images, create tables, etc. Use the "Preview" function to preview your post.**
